import impala_logo from "./images/impala-logo.png";
import impala_logo_1 from "./images/impala-1.jpg";
import impala_logo_2 from "./images/impala-2.jpg";
import profile_picture from "./images/profile-picture.jpg";

import image1 from "./images/DSC_0840.jpg";
import image2 from "./images/DSC_4411.jpg";
import image3 from "./images/DSC_8204.jpg";
import image4 from "./images/DSC_9540.jpg";

// Logo
export const logos = { impala_logo, impala_logo_1, impala_logo_2 };

export const coverPhotos = { image1, image2, image3, image4 };

// All Team Members
export const team = [
  {
    id: 0,
    name: "Steve Shammah",
    daysTrained: 6,
    daysMissed: 4,
    appearances: 60,
    dob: "26/2/1996",
    year: 1996,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 1,
    name: "Tyson Okoth",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 60,
    dob: "26/2/1996",
    year: 1996,
    team: "gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 2,
    name: "Nato Simiyu ",
    daysTrained: 8,
    daysMissed: 2,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 3,
    name: "Dancun Ekasi ",
    daysTrained: 7,
    daysMissed: 3,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 4,
    name: "Sammy Oliech",
    daysTrained: 3,
    daysMissed: 7,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 5,
    name: "Paul Mutsami",
    daysTrained: 5,
    daysMissed: 5,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 6,
    name: "Patrick Mutuku",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 7,
    name: "Richard Asante ",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 8,
    name: "Valentino Cosmas ",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 9,
    name: "Clinton Musonye",
    daysTrained: 10,
    daysMissed: 0,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 10,
    name: "Martin Juma",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 11,
    name: "George Okowa",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 12,
    name: "Quinto Oongo",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 13,
    name: "Anthony Nyandigisi",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 14,
    name: "Martin Musau",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 15,
    name: "Steve Shammah",
    daysTrained: 6,
    daysMissed: 4,
    appearances: 60,
    dob: "26/2/1996",
    year: 1996,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 16,
    name: "Tyson Okoth",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 60,
    dob: "26/2/1996",
    year: 1996,
    team: "gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 17,
    name: "Nato Simiyu ",
    daysTrained: 8,
    daysMissed: 2,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 18,
    name: "Dancun Ekasi ",
    daysTrained: 7,
    daysMissed: 3,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 19,
    name: "Sammy Oliech",
    daysTrained: 3,
    daysMissed: 7,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 20,
    name: "Paul Mutsami",
    daysTrained: 5,
    daysMissed: 5,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 21,
    name: "Patrick Mutuku",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 22,
    name: "Richard Asante ",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 23,
    name: "Valentino Cosmas ",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 24,
    name: "Clinton Musonye",
    daysTrained: 10,
    daysMissed: 0,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 25,
    name: "Martin Juma",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 26,
    name: "George Okowa",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 27,
    name: "Quinto Oongo",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 28,
    name: "Anthony Nyandigisi",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 29,
    name: "Martin Musau",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
];

export const videos = [
  { id: 0, name: "Create Group", count: "", img: "" },
  { id: 1, name: "All Videos", count: 178, img: impala_logo },
  { id: 2, name: "Kenya Cup", count: 6, img: impala_logo },
  { id: 3, name: "Interviews", count: 55, img: impala_logo_1 },
  { id: 5, name: "Match Reviews", count: 40, img: impala_logo_2 },
  { id: 6, name: "Gazelles", count: 178, img: impala_logo_2 },
  { id: 7, name: "Boks", count: 140, img: impala_logo },
  { id: 7, name: "Ladies", count: 56, img: impala_logo },
  { id: 8, name: "Swaras", count: 4, img: "" },
  { id: 9, name: "Age Grade", count: 12, img: "" },
  { id: 10, name: "Floodies", count: 150, img: "" },
  { id: 11, name: "Sevens Circuit", count: 200, img: impala_logo },
];

export const menuLinks = {
  dashboard: [
    { name: "Home", icon: "home", url: "home" },
    { name: "Training Schedule", icon: "training", url: "training" },
    {
      name: "Allowance & Payments",
      icon: "payments",
      url: "financials/payments",
    },
    { name: "Sales", icon: "sales", url: "financials/sales" },
  ],
  league: [
    { name: "League", icon: "default", url: "tournament/league" },
    { name: "7s", icon: "default", url: "tournament/sevens" },
    { name: "Floodies", icon: "default", url: "tournament/floodies" },
    { name: "Match Center", icon: "default", url: "statistics/matchcenter" },
    { name: "Team Statistics", icon: "default", url: "statistics/teamstats" },
  ],
  teams: [
    { name: "Gazelles", icon: "gazelles", url: "teams/gazelles" },
    { name: "Boks", icon: "boks", url: "teams/boks" },
    { name: "Ladies", icon: "ladies", url: "teams/ladies" },
    { name: "Age Grade", icon: "age-grade", url: "teams/agegrade" },
  ],
  website: [
    { name: "Videos", icon: "videos", url: "videos" },
    { name: "Podcasts", icon: "podcasts", url: "podcasts" },
    { name: "Socials", icon: "socials", url: "socials" },
  ],
};

// Nav Links
export const navLinks = [
  { name: "home", url: "home" },
  { name: "home", url: "home" },
  { name: "channel", url: "channel" },
  { name: "videos", url: "videos" },
  { name: "about", url: "about" },
];
export const profile = profile_picture;

export const leagueStandings = [
  {
    name: "Blak Blad",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Kenya Harlequins",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Homeboyz RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Blak Blad",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Impala Saracens",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "KCB RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Kabras Sugar RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Menengai Oilers",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "MMUST University",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Mwamba RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Nondiescript RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Nakuru RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Strathmore University",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
];

export const trainingData = [
    {
      Month: "Jan",
      current: 100,
      previous: 70,
      amt: 30,
    },
    {
      Month: "Feb",
      current: 60,
      previous: 100,
      amt: -40,
    },
    {
      Month: "Mar",
      current: 100,
      previous: 60,
      amt: 40,
    },
    {
      Month: "Apr",
      current: 50,
      previous: 100,
      amt: -50,
    },
    {
      Month: "May",
      current: 20,
      previous: 30,
      amt: -10,
    },
    {
      Month: "June",
      current: 50,
      previous: 20,
      amt: 30,
    },

    {
      Month: "Jul",
      current: 80,
      previous: 70,
      amt: 40,
    },
    {
      Month: "Aug",
      current: 60,
      previous: 80,
      amt: -20,
    },
    {
      Month: "Sep",
      current: 90,
      previous: 60,
      amt: 30,
    },
    {
      Month: "Oct",
      current: 30,
      previous: 90,
      amt: -60,
    },
    {
      Month: "Nov",
      current: 70,
      previous: 50,
      amt: 20,
    },
    {
      Month: "Dec",
      current: 80,
      previous: 70,
      amt: 10,
    },
  ];
  export const salesData = [
    {
      product: "Hoodies",
      uv: 4000,
      pv: 2400,
      amt: 2400,
    },
    {
      product: "Jerseys",
      uv: 3000,
      pv: 1398,
      amt: 2210,
    },
    {
      product: "T-Shirts",
      uv: 2000,
      pv: 9800,
      amt: 2290,
    },
    {
      product: "Caps",
      uv: 2780,
      pv: 3908,
      amt: 2000,
    },
    {
      product: "Training Kit",
      uv: 1890,
      pv: 4800,
      amt: 2181,
    },
  ];