import impalaLogo from "./images/logos/impala-logo.png";
import impalaLogo1 from "./images/logos/impala-1.jpg";
import impalaLogo2 from "./images/logos/impala-2.jpg";
import resolutionLogo from "./images/logos/ril-logo.jpg";
import stanchartLogo from "./images/logos/sc-logo.jpg";

import impalaBamboo from "./images/general/impala-bambo.jpg";
import impalaBlaze from "./images/general/impala-blaze-stand.jpg";
import impalaBlazeSunny from "./images/general/impala-blaze-sunny.jpg";
import kevoUfc from "./images/mens-team/kevo-ufc.jpg";
import kevoDanku from "./images/mens-team/kevo-danku.jpg";
import munai from "./images/mens-team/DSC_0840.jpg";
import solido from "./images/mens-team/DSC_4411.jpg";
import ajo from "./images/mens-team/DSC_8204.jpg";
import soi from "./images/mens-team/DSC_9540.jpg";
import player18 from "./images/mens-team/player_18.jpg";
import tola from "./images/mens-team/tola-2.jpg";
import phonto from "./images/mens-team/phonto.jpg";
import phontoCarry from "./images/mens-team/phonto-2.jpg";
import teamPhoto from "./images/mens-team/team_photo.jpg";
import teamPhoto2 from "./images/mens-team/team_photo-2.jpg";
import ajoKenya from "./images/mens-team/ajo-kenya.jpg";
import anderson from "./images/mens-team/anderson.jpg";
import anya from "./images/mens-team/anya.jpg";
import oscarOsir from "./images/mens-team/oscar-osir.jpg";
import physio from "./images/mens-team/physio.jpg";
import onsomu from "./images/mens-team/onsomu.jpg";
import onsomuNondies from "./images/mens-team/onsomu-nondies.jpg";
import danku from "./images/mens-team/danku.jpg";
import tyson from "./images/mens-team/tyson.jpg";
import spice from "./images/mens-team/spice.jpg";
import nyando from "./images/mens-team/nyando.jpg";
import cosy from "./images/mens-team/cosy-front.jpg";
import kimakwa from "./images/mens-team/kimakwa.jpg";
import marube from "./images/mens-team/marube.jpg";
import brian from "./images/mens-team/brian.jpg";
import boi from "./images/mens-team/boi.jpg";
import marube2 from "./images/mens-team/marube-2.jpg";
import tata from "./images/ladies-team/tata.jpg";
import tataRunning from "./images/ladies-team/tata-2.jpg";
import stella from "./images/ladies-team/stella-2.jpg";
import olympicsLadies from "./images/ladies-team/ladies-olympics.jpg";
import olympicsLadies2 from "./images/ladies-team/ladies-olympics-2.jpg";
import ladiesCelebration from "./images/ladies-team/ladies-celebration.jpg";
import rilSponsorPhoto from "./images/mens-team/ril-sponsor-photo.jpg";
import swaras from "./images/mens-team/swaras.jpg";
import ladiesRun from "./images/ladies-team/ladies-running.jpg";

// Logo
export const logos = {
  impalaLogo,
  impalaLogo1,
  impalaLogo2,
  resolutionLogo,
  stanchartLogo,
};

export const photos = {
  impalaBamboo,
  impalaBlaze,
  impalaBlazeSunny,
  kevoDanku,
  kevoUfc,
  munai,
  solido,
  ajo,
  soi,
  player18,
  phonto,
  teamPhoto,
  ajoKenya,
  anderson,
  anya,
  onsomu,
  tataRunning,
  ladiesCelebration,
  rilSponsorPhoto,
  tola,
  ladiesRun,
  swaras,
  olympicsLadies,
  olympicsLadies2,
  stella,
  tata,
  brian,
  marube,
  phontoCarry,
  teamPhoto2,
  oscarOsir,
  physio,
  onsomuNondies,
};

// All Team Members
export const team = [
  {
    id: 0,
    name: "Edmund Anya",
    daysTrained: 6,
    daysMissed: 4,
    appearances: 60,
    dob: "3w",
    year: 1996,
    team: "Gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "edmund@gmail.com",
    img: anya,
  },
  {
    id: 1,
    name: "Tyson Okoth",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 60,
    dob: "3w",
    year: 1996,
    team: "gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795256158",
    email: "tyson@gmail.com",
    img: tyson,
  },
  {
    id: 2,
    name: "Sam Kimakwa ",
    daysTrained: 8,
    daysMissed: 2,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: kimakwa,
  },
  {
    id: 3,
    name: "Dancun Ekasi ",
    daysTrained: 7,
    daysMissed: 3,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: danku,
  },
  {
    id: 4,
    name: "Alvin Marube",
    daysTrained: 3,
    daysMissed: 7,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "712345678",
    email: "shammahranks@gmail.com",
    img: marube2,
  },
  {
    id: 5,
    name: "Paul Mutsami",
    daysTrained: 5,
    daysMissed: 5,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "786595742",
    email: "paul@gmail.com",
    img: boi,
  },
  {
    id: 6,
    name: "Patrick Mutuku",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 7,
    name: "Richard Asante ",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795056853",
    email: "spice@gmail.com",
    img: spice,
  },
  {
    id: 8,
    name: "Valentino Cosmas ",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "711564789",
    email: "cosy@gmail.com",
    img: cosy,
  },
  {
    id: 9,
    name: "Clinton Musonye",
    daysTrained: 10,
    daysMissed: 0,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "tola@gmail.com",
    img: tola,
  },
  {
    id: 10,
    name: "Martin Juma",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: "",
  },
  {
    id: 11,
    name: "George Okowa",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "george@gmail.com",
    img: "",
  },
  {
    id: 12,
    name: "Quinto Oongo",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "quinto@gmail.com",
  },
  {
    id: 13,
    name: "Anthony Nyandigisi",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: nyando,
  },
  {
    id: 14,
    name: "Martin Musau",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 15,
    name: "Steve Shammah",
    daysTrained: 6,
    daysMissed: 4,
    appearances: 60,
    dob: "3w",
    year: 1996,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 16,
    name: "Tyson Okoth",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 60,
    dob: "1m",
    year: 1996,
    team: "gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 17,
    name: "Nato Simiyu ",
    daysTrained: 8,
    daysMissed: 2,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "gazelles",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 18,
    name: "Dancun Ekasi ",
    daysTrained: 7,
    daysMissed: 3,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 19,
    name: "Sammy Oliech",
    daysTrained: 3,
    daysMissed: 7,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 20,
    name: "Paul Mutsami",
    daysTrained: 5,
    daysMissed: 5,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 21,
    name: "Patrick Mutuku",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 22,
    name: "Richard Asante ",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 23,
    name: "Valentino Cosmas ",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 24,
    name: "Clinton Musonye",
    daysTrained: 10,
    daysMissed: 0,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 25,
    name: "Martin Juma",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "ladies",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 26,
    name: "George Okowa",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 27,
    name: "Quinto Oongo",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 28,
    name: "Anthony Nyandigisi",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
  {
    id: 29,
    name: "Martin Musau",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "boks",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
  },
];

export const videos = [
  { id: 0, name: "Create Group", count: "", img: "" },
  { id: 1, name: "All Videos", count: 178, img: impalaLogo },
  { id: 2, name: "Kenya Cup", count: 6, img: impalaLogo },
  { id: 3, name: "Interviews", count: 55, img: impalaLogo1 },
  { id: 5, name: "Match Reviews", count: 40, img: impalaLogo2 },
  { id: 6, name: "Gazelles", count: 178, img: impalaLogo },
  { id: 7, name: "Boks", count: 140, img: impalaLogo1 },
  { id: 7, name: "Ladies", count: 56, img: impalaLogo },
  { id: 8, name: "Swaras", count: 4, img: stanchartLogo },
  { id: 9, name: "Age Grade", count: 12, img: stanchartLogo },
  { id: 10, name: "Floodies", count: 150, img: resolutionLogo },
  { id: 11, name: "Sevens Circuit", count: 200, img: resolutionLogo },
];

export const menuLinks = {
  dashboard: [
    { name: "Home", icon: "home", url: "dashboard/home" },
    { name: "Training Schedule", icon: "training", url: "training" },
    {
      name: "Allowance & Payments",
      icon: "payments",
      url: "financials/payments",
    },
    { name: "Sales", icon: "sales", url: "financials/sales" },
  ],
  league: [
    { name: "Competitons", icon: "default", url: "tournament/league" },
    { name: "Match Center", icon: "default", url: "statistics/matchcenter" },
    { name: "Team Statistics", icon: "default", url: "statistics/teamstats" },
  ],
  teams: [
    { name: "Gazelles", icon: "gazelles", url: "teams/gazelles" },
    { name: "Boks", icon: "boks", url: "teams/boks" },
    { name: "Ladies", icon: "ladies", url: "teams/ladies" },
    { name: "Swaras", icon: "swaras", url: "teams/swaras" },
    { name: "Age Grade", icon: "age-grade", url: "teams/age-grade" },
  ],
  website: [
    { name: "Articles", icon: "articles", url: "dashboard/articles" },
    { name: "Videos", icon: "videos", url: "videos" },
    { name: "Podcasts", icon: "podcasts", url: "podcasts" },
    { name: "Socials", icon: "socials", url: "socials" },
  ],
};

// Nav Links
export const navLinks = [
  { name: "home", url: "home" },
  { name: "home", url: "home" },
  { name: "channel", url: "channel" },
  { name: "videos", url: "videos" },
  { name: "about", url: "about" },
];

export const leagueStandings = [
  {
    name: "Blak Blad",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Homeboyz RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Impala Saracens",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Kabras Sugar RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "KCB RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },

  {
    name: "Kenya Harlequins",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Menengai Oilers",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "MMUST University",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Mwamba RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Nondiescript RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Nakuru RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Strathmore University",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
];

export const trainingData = [
  {
    Month: "Jan",
    current: 100,
    previous: 70,
    amt: 30,
  },
  {
    Month: "Feb",
    current: 60,
    previous: 100,
    amt: -40,
  },
  {
    Month: "Mar",
    current: 100,
    previous: 60,
    amt: 40,
  },
  {
    Month: "Apr",
    current: 50,
    previous: 100,
    amt: -50,
  },
  {
    Month: "May",
    current: 20,
    previous: 30,
    amt: -10,
  },
  {
    Month: "June",
    current: 50,
    previous: 20,
    amt: 30,
  },

  {
    Month: "Jul",
    current: 80,
    previous: 70,
    amt: 40,
  },
  {
    Month: "Aug",
    current: 60,
    previous: 80,
    amt: -20,
  },
  {
    Month: "Sep",
    current: 90,
    previous: 60,
    amt: 30,
  },
  {
    Month: "Oct",
    current: 30,
    previous: 90,
    amt: -60,
  },
  {
    Month: "Nov",
    current: 70,
    previous: 50,
    amt: 20,
  },
  {
    Month: "Dec",
    current: 80,
    previous: 70,
    amt: 10,
  },
];
export const salesData = [
  {
    product: "Hoodies",
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    product: "Jerseys",
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    product: "T-Shirts",
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    product: "Caps",
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    product: "Training Kit",
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
];
