import impalaLogo from "./images/logos/impala-logo.png";
import impalaLogo1 from "./images/logos/impala-1.jpg";
import impalaLogo2 from "./images/logos/impala-2.jpg";
import floodies from "./images/logos/floodies-logo.jpg";
import resolutionLogo from "./images/logos/ril-logo.jpg";
import blazeLogo from "./images/logos/blaze-logo.png";
import saracensLogo from "./images/logos/saracens-logo.svg";
import stanchartLogo from "./images/logos/sc-logo.jpg";
import hbrLogo from "./images/logos/hbr-logo.jpg";
import kabrasLogo from "./images/logos/kabras-logo.jpg";
import kcbLogo from "./images/logos/kcb-logo.jpg";
import kruLogo from "./images/logos/kru-logo.jpg";
import mmustLogo from "./images/logos/mmust-logo.png";
import mwambaLogo from "./images/logos/mwamba-logo.jpg";
import quinsLogo from "./images/logos/quins-logo.jpg";
import nakuruLogo from "./images/logos/nakuru-logo.jpg";
import nondiesLogo from "./images/logos/nondies-logo.jpg";
import oilersLogo from "./images/logos/oilers-logo.jpg";
import strathmoreLogo from "./images/logos/strathmore-logo.jpg";
import bladLogo from "./images/logos/blad-logo.png";
import kenyaCupLogo from "./images/logos/kenya-cup-logo.png";

import impalaBamboo from "./images/general/impala-bambo.jpg";
import impalaBlaze from "./images/general/impala-blaze-stand.jpg";
import impalaBlazeSunny from "./images/general/impala-blaze-sunny.jpg";
import kevoUfc from "./images/mens-team/kevo-ufc.jpg";
import kevoDanku from "./images/mens-team/kevo-danku.jpg";
import munai from "./images/mens-team/DSC_0840.jpg";
import solido from "./images/mens-team/bill-okoyo.jpg";
import ajo from "./images/mens-team/DSC_8204.jpg";
import soi from "./images/mens-team/DSC_9540.jpg";
import player18 from "./images/mens-team/player_18.jpg";
import tola from "./images/mens-team/tola-2.jpg";
import phonto from "./images/mens-team/phonto.jpg";
import phontoCarry from "./images/mens-team/phonto-2.jpg";
import teamPhoto from "./images/mens-team/team_photo.jpg";
import teamPhoto2 from "./images/mens-team/team_photo-2.jpg";
import ajoKenya from "./images/mens-team/ajo-kenya.jpg";
import anderson from "./images/mens-team/anderson.jpg";
import anya from "./images/mens-team/anya.jpg";
import oscarOsir from "./images/mens-team/oscar-osir.jpg";
import mitchOcholla from "./images/mens-team/mitch-ocholla.jpg";
import alphaAcademy from "./images/mens-team/alpha-academy.jpg";
import kakaiAlpha from "./images/mens-team/kakai-alpha-academy.jpg";
import physio from "./images/mens-team/physio.jpg";
import shammah from "./images/mens-team/shammah.jpg";
import onsomu from "./images/mens-team/onsomu.jpg";
import onsomuNondies from "./images/mens-team/onsomu-nondies.jpg";
import danku from "./images/mens-team/danku.jpg";
import tyson from "./images/mens-team/tyson.jpg";
import spice from "./images/mens-team/spice.jpg";
import nyando from "./images/mens-team/nyando.jpg";
import cosy from "./images/mens-team/cosy-front.jpg";
import kimakwa from "./images/mens-team/kimakwa.jpg";
import marube from "./images/mens-team/marube.jpg";
import brian from "./images/mens-team/brian.jpg";
import boi from "./images/mens-team/boi.jpg";
import muchiri from "./images/mens-team/anthony-muchiri.jpg";
import marube2 from "./images/mens-team/marube-2.jpg";
import tata from "./images/ladies-team/tata.jpg";
import tataRunning from "./images/ladies-team/tata-2.jpg";
import stella from "./images/ladies-team/stella-kenya.jpg";
import anne from "./images/ladies-team/anne-goreti.jpg";
import diana from "./images/ladies-team/diana-awino.jpg";
import dianaKemunto from "./images/ladies-team/diana-kemunto.jpg";
import winnie from "./images/ladies-team/winnie.jpg";
import judith from "./images/ladies-team/judith-auma.jpg";
import mitchelleAkinyi from "./images/ladies-team/mitchelle-akinyi.jpg";
import mitchelle from "./images/ladies-team/mitchelle.jpg";
import olympicsLadies from "./images/ladies-team/ladies-olympics.jpg";
import olympicsLadies2 from "./images/ladies-team/ladies-olympics-2.jpg";
import ladiesCelebration from "./images/ladies-team/ladies-celebration.jpg";
import rilSponsorPhoto from "./images/mens-team/ril-sponsor-photo.jpg";
import rilSponsorPhoto1 from "./images/mens-team/ril-sponsor-photo-1.jpg";
import swaras from "./images/mens-team/swaras.jpg";
import ladiesRun from "./images/ladies-team/ladies-running.jpg";
import coding from "./images/anonymous-hacker.jpg";
import situationControl from "./images/situation.jpeg";

// Products Imports
import awayKitReplicaW from "./images/merchandise/away kit-replica-w-2016.jpg";
import awayKitReplicaM from "./images/merchandise/away kit-replica-m-2016.jpg";
import billGithinji from "./images/merchandise/bill-githinji-branded.jpg";
import mato from "./images/merchandise/mato-branded.jpg";
import spanner from "./images/merchandise/spanner-hoodie.jpg";
import damimaKitted from "./images/merchandise/damima-branded.jpg";
import wristBands from "./images/merchandise/bands.jpg";
import jacketKids from "./images/merchandise/jacket-kids.jpg";
import trackSuitBlueKids from "./images/merchandise/track-suit-navy-blue-kids.jpg";
import trackSuitBlackWomen from "./images/merchandise/track-suit-black-ladies.jpg";
import trackJacket from "./images/merchandise/track-jacket-red.jpg";
import hoodieBlackMin from "./images/merchandise/hoodie-black-minimal.jpg";
import travelHat from "./images/merchandise/hat-travel.jpg";
import capOpenRed from "./images/merchandise/cap-open.jpg";
import hoodieGrey from "./images/merchandise/hoodie-grey.JPG";
import hoodieBlack from "./images/merchandise/hoodie-black.JPG";
import hoodieRed from "./images/merchandise/hoodie-red.JPG";
import eatRugbyTshirt from "./images/merchandise/eat_sleep_rugby.jpg";
import floodies2016 from "./images/merchandise/tshirt-black-floodies.jpg";
import pinkTshirtWomen from "./images/merchandise/tshirt-pink-women.jpg";
import blackTshirtWomen from "./images/merchandise/tshirt-black-women.jpg";
import blackTshirtMen from "./images/merchandise/tshirt-black-men.jpg";
import redTshirtMen from "./images/merchandise/tshirt-red-men.jpg";
import blackSweatShirtMen from "./images/merchandise/sweat-shirt-black-men.jpg";
import waterBottleWhite from "./images/merchandise/water-bottle-white.jpg";
import poloTshirtRed from "./images/merchandise/polo-tshirt-red.jpg";
import hoodiesRedMinW from "./images/merchandise/hoodie-red-minimal-women.jpg";
import hoodiesRedMinM from "./images/merchandise/hoodie-red-minimal-men.jpg";
import cupWhite from "./images/merchandise/cup-ceramic-white.jpg";
import cupMetallic from "./images/merchandise/cup-metallic.jpg";

// Products

// Logo
export const logos = {
  impalaLogo,
  impalaLogo1,
  impalaLogo2,
  floodies,
  resolutionLogo,
  stanchartLogo,
  saracensLogo,
  blazeLogo,
  quinsLogo,
  kcbLogo,
  kabrasLogo,
  mwambaLogo,
  mmustLogo,
  oilersLogo,
  nondiesLogo,
  nakuruLogo,
  hbrLogo,
  kenyaCupLogo,
  kruLogo,
  strathmoreLogo,
  bladLogo,
};

export const photos = {
  coding,
  billGithinji,
  spanner,
  mato,
  hoodieBlack,
  hoodieRed,
  impalaBamboo,
  impalaBlaze,
  impalaBlazeSunny,
  kevoDanku,
  kevoUfc,
  munai,
  solido,
  ajo,
  soi,
  player18,
  phonto,
  teamPhoto,
  ajoKenya,
  anderson,
  anya,
  onsomu,
  tataRunning,
  ladiesCelebration,
  rilSponsorPhoto,
  tola,
  ladiesRun,
  swaras,
  olympicsLadies,
  olympicsLadies2,
  stella,
  tata,
  brian,
  marube,
  phontoCarry,
  teamPhoto2,
  oscarOsir,
  physio,
  onsomuNondies,
};

// All Team Members
export const team = [
  {
    id: 0,
    name: "Edmund Anya",
    daysTrained: 6,
    daysMissed: 4,
    appearances: 60,
    dob: "1/1/1997",
    year: 1996,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "edmund@gmail.com",
    img: anya,
  },
  {
    id: 1,
    name: "Tyson Okoth",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 60,
    dob: "1/1/1996",
    year: 1996,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795256158",
    email: "tyson@gmail.com",
    img: tyson,
  },
  {
    id: 2,
    name: "Sam Kimakwa ",
    daysTrained: 8,
    daysMissed: 2,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: kimakwa,
  },
  {
    id: 3,
    name: "Dancun Ekasi ",
    daysTrained: 7,
    daysMissed: 3,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: danku,
  },
  {
    id: 4,
    name: "Alvin Marube",
    daysTrained: 3,
    daysMissed: 7,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "712345678",
    email: "shammahranks@gmail.com",
    img: marube2,
  },
  {
    id: 5,
    name: "Paul Mutsami",
    daysTrained: 5,
    daysMissed: 5,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "786595742",
    email: "paul@gmail.com",
    img: boi,
  },
  {
    id: 6,
    name: "Rainer Omondi",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 7,
    name: "Richard Asante ",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795056853",
    email: "spice@gmail.com",
    img: spice,
  },
  {
    id: 8,
    name: "Valentino Cosmas ",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "711564789",
    email: "cosy@gmail.com",
    img: cosy,
  },
  {
    id: 9,
    name: "Clinton Musonye",
    daysTrained: 10,
    daysMissed: 0,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "tola@gmail.com",
    img: tola,
  },
  {
    id: 10,
    name: "Martin Juma",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 11,
    name: "George Okowa",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "george@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 12,
    name: "Quinto Oongo",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "quinto@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 13,
    name: "Anthony Nyandigisi",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: nyando,
  },
  {
    id: 14,
    name: "Martin Musau",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo2,
  },
  {
    id: 15,
    name: "Steve Shammah",
    daysTrained: 6,
    daysMissed: 4,
    appearances: 60,
    dob: "3w",
    year: 1996,
    team: "Swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: shammah,
  },
  {
    id: 16,
    name: "Anderson Oduor",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 60,
    dob: "1m",
    year: 1996,
    team: "Swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: anderson,
  },
  {
    id: 17,
    name: "Nato Simiyu ",
    daysTrained: 8,
    daysMissed: 2,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 18,
    name: "Milton Obote",
    daysTrained: 7,
    daysMissed: 3,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: player18,
  },
  {
    id: 19,
    name: "Sammy Oliech",
    daysTrained: 3,
    daysMissed: 7,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 20,
    name: "Maxwell Otieno",
    daysTrained: 5,
    daysMissed: 5,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo2,
  },
  {
    id: 21,
    name: "Patrick Mutuku",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 22,
    name: "Joshua Momanyi",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 23,
    name: "Davies Makori",
    daysTrained: 2,
    daysMissed: 8,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Men",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo1,
  },
  {
    id: 24,
    name: "Anthony Jerym",
    daysTrained: 10,
    daysMissed: 0,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Swaras",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: ajoKenya,
  },
  {
    id: 25,
    name: "Mitchelle Impala",
    daysTrained: 9,
    daysMissed: 1,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Women",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: mitchelleAkinyi,
  },
  {
    id: 26,
    name: "Stella Wafula",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Women",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: stella,
  },
  {
    id: 27,
    name: "Christabel Lindo",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Women",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: tata,
  },
  {
    id: 28,
    name: "Mary Ochieng",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Coaches",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo,
  },
  {
    id: 29,
    name: "Diana Kemunto",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Women",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: dianaKemunto,
  },
  {
    id: 30,
    name: "Winnie Owino",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Women",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: winnie,
  },
  {
    id: 31,
    name: "Diana Awino",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Women",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: diana,
  },
  {
    id: 32,
    name: "Oscar Osir",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Coaches",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: oscarOsir,
  },
  {
    id: 33,
    name: "Nick Abok",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Coaches",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo,
  },
  {
    id: 34,
    name: "Innocent Simiyu",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Coaches",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo,
  },
  {
    id: 35,
    name: "Frank Ndong",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Coaches",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo,
  },
  {
    id: 36,
    name: "Fred Ollows",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Coaches",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: impalaLogo,
  },
  {
    id: 37,
    name: "Chris Makachia",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Coaches",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: physio,
  },
  {
    id: 38,
    name: "Anthony Muchiri",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Coaches",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: muchiri,
  },
  {
    id: 39,
    name: "Judith Auma",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Women",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: judith,
  },
  {
    id: 40,
    name: "Anne Goreti",
    daysTrained: 4,
    daysMissed: 6,
    appearances: 400,
    dob: "1/1/1988",
    year: 1988,
    team: "Women",
    socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
    phone: "795058630",
    email: "shammahranks@gmail.com",
    img: anne,
  },
];

export const videos = [
  { id: 0, name: "Create Group", count: "", img: "" },
  { id: 1, name: "All Videos", count: 178, img: impalaLogo },
  { id: 2, name: "Kenya Cup", count: 6, img: impalaLogo },
  { id: 3, name: "Interviews", count: 55, img: impalaLogo1 },
  { id: 5, name: "Match Reviews", count: 40, img: impalaLogo2 },
  { id: 6, name: "Men", count: 178, img: impalaLogo },
  { id: 7, name: "Boks", count: 140, img: impalaLogo1 },
  { id: 7, name: "Ladies", count: 56, img: impalaLogo },
  { id: 8, name: "Swaras", count: 4, img: stanchartLogo },
  { id: 9, name: "Age Grade", count: 12, img: stanchartLogo },
  { id: 10, name: "Floodies", count: 150, img: resolutionLogo },
  { id: 11, name: "Sevens Circuit", count: 200, img: resolutionLogo },
];

export const menuLinks = {
  dashboard: [
    { name: "Home", icon: "home", url: "dashboard/home" },
    { name: "Training Schedule", icon: "training", url: "training" },
    {
      name: "Allowance & Payments",
      icon: "payments",
      url: "financials/payments",
    },
    { name: "Sales", icon: "sales", url: "financials/sales" },
  ],
  league: [
    { name: "Competitons", icon: "default", url: "tournament/league" },
    { name: "Match Center", icon: "default", url: "statistics/matchcenter" },
    { name: "Team Statistics", icon: "default", url: "statistics/teamstats" },
  ],
  teams: [
    { name: "Men", icon: "Men", url: "teams/Men" },
    { name: "Boks", icon: "boks", url: "teams/Boks" },
    { name: "Ladies", icon: "ladies", url: "teams/Women" },
    { name: "Swaras", icon: "swaras", url: "teams/Swaras" },
    { name: "Age Grade", icon: "age-grade", url: "teams/age-grade" },
  ],
  website: [
    { name: "Articles", icon: "articles", url: "dashboard/articles" },
    { name: "Videos", icon: "videos", url: "videos" },
    { name: "Podcasts", icon: "podcasts", url: "podcasts" },
    { name: "Socials", icon: "socials", url: "socials" },
  ],
};

// Nav Links
export const navLinks = [
  { name: "home", url: "home" },
  { name: "home", url: "home" },
  { name: "channel", url: "channel" },
  { name: "videos", url: "videos" },
  { name: "about", url: "about" },
];
export const partners = [
  {
    id: 0,
    name: "Resolution Insurance",
    url: "resolution",
    website: "resolution.co.ke",
    img: resolutionLogo,
    about:
      "Resolution Insurance Kenya is a Kenyan insurance brand trusted by individuals and businesses who enjoy our well designed and unique insurance covers.",
    tag: "Offical Sponsor of Impala.",
  },
  {
    id: 1,
    name: "Standard Chartered Bank",
    url: "stanchart",
    website: "resolution.co.ke",
    img: stanchartLogo,
    about:
      "At Standard Chartered Kenya, we help you achieve financial freedom with products such as savings accounts, personal loans, credit cards & wealth solutions.",
    tag: "Offical Academy Sponsor",
  },
  {
    id: 2,
    name: "Saracens Official",
    url: "saracens",
    website: "saracens.com",
    img: saracensLogo,
    about:
      "Established in 1876, Saracens Rugby Club are London's premier rugby club competing on the Gallagher Premiership, The European Champions Cup, The Tyrells Premier 15s and the Premiership Rugby Cup.",
    tag: "Global Network Partneship",
  },
  {
    id: 3,
    name: "Blaze",
    url: "blaze",
    website: "blaze.co.ke",
    img: blazeLogo,
    about:
      "BLAZE is a youth network. We celebrate their passion to succeed in unconventional careers.",
    tag: "Offical Floodlit Sponsor",
  },
];
export const leagueStandings = [
  {
    name: "Blak Blad",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Homeboyz RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Impala Saracens",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Kabras Sugar RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "KCB RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },

  {
    name: "Kenya Harlequins",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Menengai Oilers",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "MMUST University",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Mwamba RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Nondiescript RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Nakuru RFC",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
  {
    name: "Strathmore University",
    played: 1,
    won: 1,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 20,
    points: 0,
  },
];

export const trainingData = [
  {
    Month: "Jan",
    current: 100,
    previous: 70,
    amt: 30,
  },
  {
    Month: "Feb",
    current: 60,
    previous: 100,
    amt: -40,
  },
  {
    Month: "Mar",
    current: 100,
    previous: 60,
    amt: 40,
  },
  {
    Month: "Apr",
    current: 50,
    previous: 100,
    amt: -50,
  },
  {
    Month: "May",
    current: 20,
    previous: 30,
    amt: -10,
  },
  {
    Month: "June",
    current: 50,
    previous: 20,
    amt: 30,
  },

  {
    Month: "Jul",
    current: 80,
    previous: 70,
    amt: 40,
  },
  {
    Month: "Aug",
    current: 60,
    previous: 80,
    amt: -20,
  },
  {
    Month: "Sep",
    current: 90,
    previous: 60,
    amt: 30,
  },
  {
    Month: "Oct",
    current: 30,
    previous: 90,
    amt: -60,
  },
  {
    Month: "Nov",
    current: 70,
    previous: 50,
    amt: 20,
  },
  {
    Month: "Dec",
    current: 80,
    previous: 70,
    amt: 10,
  },
];
export const salesData = [
  {
    product: "Hoodies",
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    product: "Jerseys",
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    product: "T-Shirts",
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    product: "Caps",
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    product: "Training Kit",
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
];

export const products = [
  {
    id: 0,
    name: "Away Kit - 2016",
    img: awayKitReplicaW,
    price: "4500",
    sizes: ["S", "L", "XL"],
    details: "Women's Away Kit - Replica Jersey",
    inStock: true,
    category: ["women", "kit", "away"],
    color: "white",
  },
  {
    id: 1,
    name: "Hoodie Black",
    img: hoodieBlack,
    price: "4000",
    sizes: ["S", "L", "XL"],
    details: "Hoodie Elite Fan",
    inStock: true,
    category: ["Hoodies", "men", "women"],
    color: "Black",
  },
  {
    id: 2,
    name: "Jacket Kids",
    img: jacketKids,
    price: "1500",
    sizes: ["S", "L", "XL"],
    details: "Kids Short Sleeved jacket",
    inStock: true,
    category: ["kids", "jacket"],
    color: "Black",
  },
  {
    id: 3,
    name: "Track Suit",
    img: trackSuitBlueKids,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: "Kids Track Suit Kids",
    inStock: true,
    category: ["kids", "jacket"],
    color: "Navy Blue",
  },
  {
    id: 4,
    name: "Wrist Bands",
    img: wristBands,
    price: "100",
    sizes: ["S", "L", "XL"],
    details: "Wrist Bands - Red & White",
    inStock: true,
    category: ["accessories", "wrist bands"],
    color: "Red/White",
  },
  {
    id: 5,
    name: "Track Suit",
    img: trackSuitBlackWomen,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: " Womens Track Suit",
    inStock: true,
    category: ["women", "track suit"],
    color: "Black",
  },
  {
    id: 6,
    name: "Training Jacket",
    img: trackJacket,
    price: "2000",
    sizes: ["S", "L", "XL"],
    details: "Men's training jacket",
    inStock: true,
    category: ["men", "track suit", "jacket"],
    color: "Red",
  },
  {
    id: 7,
    name: "Sweat Shirt",
    img: blackSweatShirtMen,
    price: "2200",
    sizes: ["S", "L", "XL"],
    details: " Men's Sweat Shirt",
    inStock: true,
    category: ["men", "sweat-shirt"],
    color: "Black",
  },
  {
    id: 8,
    name: "Hoodie Min",
    img: hoodieBlackMin,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: " Hoodie Min",
    inStock: true,
    category: ["men", "track suit", "jacket", "women"],
    color: "Black",
  },
  {
    id: 9,
    name: "Polo T-Shirt",
    img: poloTshirtRed,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: " Polo T-Shirt",
    inStock: true,
    category: ["men", "tshirt", "jacket"],
    color: "Red",
  },
  {
    id: 10,
    name: "Water Bottle",
    img: waterBottleWhite,
    price: "700",
    sizes: ["S", "L", "XL"],
    details: "Metallic water bottle",
    inStock: true,
    category: ["accessories", "water bottle"],
    color: "White",
  },
  {
    id: 11,
    name: "Travel Hat",
    img: travelHat,
    price: "700",
    sizes: ["S", "L", "XL"],
    details: "Impala Travel Hat",
    inStock: true,
    category: ["accessories", "hat", "cap"],
    color: "Beige",
  },
  {
    id: 12,
    name: "T-Shirt Women",
    img: pinkTshirtWomen,
    price: "700",
    sizes: ["S", "L", "XL"],
    details: " Women T-Shirt",
    inStock: true,
    category: ["tshirt", "women"],
    color: "Pink",
  },
  {
    id: 13,
    name: "T-Shirt Women",
    img: blackTshirtWomen,
    price: "700",
    sizes: ["S", "L", "XL"],
    details: " Women T-Shirt",
    inStock: true,
    category: ["tshirt", "women"],
    color: "Black",
  },
  {
    id: 14,
    name: "T-Shirt Men",
    img: blackTshirtMen,
    price: "700",
    sizes: ["S", "L", "XL"],
    details: " Men T-Shirt",
    inStock: true,
    category: ["tshirt", "men"],
    color: "Black",
  },
  {
    id: 15,
    name: "Cap Open",
    img: capOpenRed,
    price: "1100",
    sizes: ["S", "L", "XL"],
    details: "Cap Open ",
    inStock: true,
    category: ["cap", "accessories"],
    color: "Red",
  },
  {
    id: 16,
    name: "Hoodie Elite Fan",
    img: hoodieGrey,
    price: "1100",
    sizes: ["S", "L", "XL"],
    details: "Hoodie Elite Fan",
    inStock: true,
    category: ["hoodie", "men", "women"],
    color: "Grey",
  },
  {
    id: 17,
    name: "T-Shirt Floodies",
    img: floodies2016,
    price: "1100",
    sizes: ["S", "L", "XL"],
    details: "Floodlit T-Shirt",
    inStock: true,
    category: ["tshirt", "floodies", "men"],
    color: "Black",
  },
  {
    id: 18,
    name: " Eat - Sleep - Rugby - Repeat",
    img: eatRugbyTshirt,
    price: "1000",
    sizes: ["S", "L", "XL"],
    details: "Eat Sleep Impala Rugby",
    inStock: true,
    category: ["men", "floodies", "tshirt"],
    color: "Black",
  },
  {
    id: 18,
    name: "Hoodie Min",
    img: hoodiesRedMinM,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: "Hoodie Min Black",
    inStock: true,
    category: ["men", "track suit", "jacket", "men"],
    color: "Black",
  },
  {
    id: 19,
    name: "Hoodie Min",
    img: hoodiesRedMinW,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: "Hoodie Min Red",
    inStock: true,
    category: ["track suit", "jacket", "women"],
    color: "Red",
  },
  {
    id: 20,
    name: "Away Kit 2016",
    img: awayKitReplicaM,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: "Away Kit 2016 Replica - Men",
    inStock: true,
    category: ["men", "track suit", "jacket"],
    color: "White",
  },
  {
    id: 21,
    name: "Women Tshirt",
    img: damimaKitted,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: "Women T-shirt",
    inStock: true,
    category: ["women", "track suit", "tshirt"],
    color: "Red",
  },
  {
    id: 22,
    name: "Cup Ceramic",
    img: cupWhite,
    price: "1100",
    sizes: ["S", "L", "XL"],
    details: "Cup Ceramic",
    inStock: true,
    category: ["accessories", "cup"],
    color: "White",
  },
  {
    id: 23,
    name: "Cup Metallic",
    img: cupMetallic,
    price: "1600",
    sizes: ["S", "L", "XL"],
    details: "Cup Metallic",
    inStock: true,
    category: ["accessories", "cup"],
    color: "Metallic",
  },
  {
    id: 24,
    name: "Impala T-Shirt",
    img: redTshirtMen,
    price: "3500",
    sizes: ["S", "L", "XL"],
    details: "T-Shirt - Red",
    inStock: true,
    category: ["tshirt", "men"],
    color: "Red",
  },
];

export const allFixtures = {
  Men: [
    {
      id: 0,
      opponent: "Harlequins",
      logo: quinsLogo,
      day: "Saturday 27 November 2021",
      kickOff: "15:00",
      home: false,
      venue: "RFUEA",
      scores: "28-12",
      played: true,
      league: "Kenya Cup",
    },
    {
      id: 1,
      opponent: "Oilers",
      logo: oilersLogo,
      day: "Saturday 5 November 2021",
      kickOff: "15:00",
      home: true,
      venue: "Impala Grounds",
      scores: "28-12",
      played: true,
      league: "Kenya Cup",
    },

    {
      id: 2,
      opponent: "Strathmore",
      logo: strathmoreLogo,
      day: "Saturday 12 December 2021",
      kickOff: "15:00",
      home: false,
      venue: "Strathmore",
      scores: "28-12",
      played: true,
      league: "Kenya Cup",
    },
    {
      id: 3,
      opponent: "Kabras",
      logo: kabrasLogo,
      day: "Saturday 19 December 2021",
      kickOff: "15:00",
      home: true,
      venue: "Impala Grounds",
      scores: "28-12",
      played: true,
      league: "Kenya Cup",
    },
    {
      id: 4,
      opponent: "KCB",
      logo: kcbLogo,
      day: "Saturday 8 January 2022",
      kickOff: "15:00",
      home: false,
      venue: "Den, Ruaraka",
      scores: "47-0",
      played: true,
      league: "Kenya Cup",
    },
    {
      id: 5,
      opponent: "Homeboyz",
      logo: hbrLogo,
      day: "Saturday 15 January 2022",
      kickOff: "15:00",
      home: false,
      venue: "Show Grounds, Jamhuri",
      scores: "",
      played: false,
      league: "Kenya Cup",
    },
    {
      id: 6,
      opponent: "Nakuru",
      logo: nakuruLogo,
      day: "Saturday 22 January 2022",
      kickOff: "15:00",
      home: true,
      venue: "Impala Grounds",
      scores: "",
      played: false,
      league: "Kenya Cup",
    },
    {
      id: 7,
      opponent: "Mwamba",
      logo: mwambaLogo,
      day: "Saturday 29 January 2022",
      kickOff: "15:00",
      home: true,
      venue: "Impala Grounds",
      scores: "",
      played: false,
      league: "Kenya Cup",
    },
    {
      id: 8,
      opponent: "Nondiescript",
      logo: nondiesLogo,
      day: "Saturday 5 February 2022",
      kickOff: "15:00",
      home: false,
      venue: "Ngong Racecourse",
      scores: "",
      played: false,
      league: "Kenya Cup",
    },
    {
      id: 9,
      opponent: "Blak Blad",
      logo: bladLogo,
      day: "Saturday 12 February 2022",
      kickOff: "15:00",
      home: false,
      venue: "Blad Bin",
      scores: "",
      played: false,
      league: "Kenya Cup",
    },
    {
      id: 10,
      opponent: "MMUST",
      logo: mmustLogo,
      day: "Saturday 19 February 2022",
      kickOff: "15:00",
      home: false,
      venue: "Nandi Bears",
      scores: "",
      played: false,
      league: "Kenya Cup",
    },
  ],
  Women: [
    {
      id: 0,
      opponent: "Harlequins",
      logo: quinsLogo,
      day: "Saturday 27 November 2021",
      kickOff: "12:00",
      home: false,
      venue: "RFUEA",
      scores: "9-62",
      played: true,
      league: "Womens League",
    },

    {
      id: 2,
      opponent: "Northern Surbubs",
      logo: kcbLogo,
      day: "Saturday 12 December 2021",
      kickOff: "12:00",
      home: true,
      venue: "Impala Grounds",
      scores: "58-12",
      played: true,
      league: "Womens League",
    },
    {
      id: 3,
      opponent: "Mwamba",
      logo: mwambaLogo,
      day: "Saturday 19 December 2021",
      kickOff: "15:00",
      home: false,
      venue: "Impala Grounds",
      scores: "54-5",
      played: true,
      league: "Womens League",
    },
    {
      id: 4,
      opponent: "Nakuru",
      logo: nakuruLogo,
      day: "Saturday 8 January 2022",
      kickOff: "12:00",
      home: false,
      venue: "Ask Showground, Ruaraka",
      scores: "",
      played: false,
      league: "Womens League",
    },
    {
      id: 5,
      opponent: "Homeboyz",
      logo: hbrLogo,
      day: "Saturday 15 January 2022",
      kickOff: "12:00",
      home: false,
      venue: "Show Grounds, Jamhuri",
      scores: "",
      played: false,
      league: "Womens League",
    },
    {
      id: 6,
      opponent: "Nakuru",
      logo: nakuruLogo,
      day: "Saturday 22 January 2022",
      kickOff: "12:00",
      home: true,
      venue: "Impala Grounds",
      scores: "",
      played: false,
      league: "Womens League",
    },
    {
      id: 7,
      opponent: "Mwamba",
      logo: mwambaLogo,
      day: "Saturday 29 January 2022",
      kickOff: "15:00",
      home: true,
      venue: "Impala Grounds",
      scores: "",
      played: false,
      league: "Womens League",
    },
    {
      id: 8,
      opponent: "Blak Blad",
      logo: bladLogo,
      day: "Saturday 5 February 2022",
      kickOff: "15:00",
      home: false,
      venue: "Blad Bin",
      scores: "",
      played: false,
      league: "Womens League",
    },
  ],
  Swaras: [
    {
      id: 0,
      opponent: "Harlequins",
      logo: quinsLogo,
      day: "Saturday 27 November 2021",
      kickOff: "10:00",
      home: false,
      venue: "RFUEA",
      scores: "28-12",
      played: true,
      league: "Nationwide",
    },
    {
      id: 1,
      opponent: "Daystar",
      logo: mmustLogo,
      day: "Saturday 5 December 2021",
      kickOff: "10:00",
      home: true,
      venue: "Impala Grounds",
      scores: "12-28",
      played: true,
      league: "Nationwide",
    },
    {
      id: 2,
      opponent: "Shamas",
      logo: strathmoreLogo,
      day: "Saturday 12 December 2021",
      kickOff: "15:00",
      home: false,
      venue: "Strathmore",
      scores: "28-12",
      played: true,
      league: "Nationwide",
    },
    {
      id: 3,
      opponent: "Brumbies",
      logo: kabrasLogo,
      day: "Saturday 19 December 2021",
      kickOff: "15:00",
      home: false,
      venue: "Impala Grounds",
      scores: "28-12",
      played: true,
      league: "Nationwide",
    },
    {
      id: 4,
      opponent: "Comras",
      logo: kcbLogo,
      day: "Saturday 8 January 2022",
      kickOff: "15:00",
      home: false,
      venue: "Den, Ruaraka",
      scores: "",
      played: false,
      league: "Nationwide",
    },
    {
      id: 5,
      opponent: "Moh Spice",
      logo: hbrLogo,
      day: "Saturday 15 January 2022",
      kickOff: "15:00",
      home: false,
      venue: "Show Grounds, Jamhuri",
      scores: "",
      played: false,
      league: "Nationwide",
    },
    {
      id: 6,
      opponent: "CUEA",
      logo: nakuruLogo,
      day: "Saturday 22 January 2022",
      kickOff: "15:00",
      home: true,
      venue: "Impala Grounds",
      scores: "",
      played: false,
      league: "Nationwide",
    },
    {
      id: 7,
      opponent: "KCA",
      logo: mwambaLogo,
      day: "Saturday 29 January 2022",
      kickOff: "15:00",
      home: true,
      venue: "Impala Grounds",
      scores: "",
      played: false,
      league: "Nationwide",
    },
    {
      id: 8,
      opponent: "Zetech",
      logo: nondiesLogo,
      day: "Saturday 5 February 2022",
      kickOff: "15:00",
      home: false,
      venue: "Ngong Racecourse",
      scores: "",
      played: false,
      league: "Nationwide",
    },
  ],
};

export const localArticles = [
  {
    id: 0,
    title: "Kenya Cup Is Back",
    headline: "The off-season is complete. Match day 1 confirmed!",
    image_1: teamPhoto,
    image_2: anderson,
    type: "news",
    tags: "Kenya Cup, Off-Season, Men",
    author: "Impala Media",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
  },
  {
    id: 1,
    title: "The Millers Win On Tour",
    headline: "Defeat at the Impala Grounds",
    image_1: tola,
    caption_1: "Tola in previous match against Kabras",
    image_2: kabrasLogo,
    caption_2:
      "Ball retention at the lineout area was impressive from the lads",
    type: "News",
    tags: "Impala, Men, Kabras",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 2,
    title: "Osir appointed head coach",
    headline: "Double O gets to manage the team afters seasons of involvement.",
    image_1: oscarOsir,
    image_2: kimakwa,
    type: "news",
    tags: "Kenya Cup, Oscar Osir, Mitch Ocholla, Men, Club",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 3,
    title: "Mitch Ocholla leaves.",
    headline: "Mitch ocholla heads back to Nakuru.",
    image_1: mitchOcholla,
    image_2: oscarOsir,
    type: "update",
    tags: "Kenya Cup, Oscar Osir, Mitch Ocholla, Men, Club",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 4,
    title: "Match Day One!!.",
    headline: "Derby Day.",
    image_1: kevoDanku,
    image_2: kevoUfc,
    type: "news",
    tags: "Kenya Cup, Harlequins, Derby, Nato Simiyu, Men",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 5,
    title: "Young Boks now Gazelles",
    headline: "From the academy to the big league.",
    image_1: cosy,
    image_2: spice,
    type: "article",
    tags: "Men, Swaras, Kenya Cup",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Sponsor",
  },
  {
    id: 6,
    title: "Academy to resume training",
    headline: "Impala Swaras to begin preparations for the nationwide league!",
    image_1: swaras,
    image_2: swaras,
    type: "update",
    tags: "Academy, Age grade, Swaras ",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 7,
    title: "The ladies' form continues",
    headline:
      "Ladies team caps off an impresive season with first place finish.",
    image_1: ladiesCelebration,
    image_2: ladiesRun,
    type: "news",
    tags: "Women, Ladies Tournament, ",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 8,
    title: "Phonto Returns From Kenya Duty.",
    headline:
      "Musonye talks about his recent caps and his experience of the SA Tour.",
    image_1: phonto,
    image_2: phontoCarry,
    type: "feature",
    tags: "Kenya Cup, Phonto, Elkeans Musonye, Men",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 9,
    title: "Injury Update.",
    headline:
      "The team physio gives update on injury list and possible return.",
    image_1: physio,
    image_2: solido,
    type: "update",
    tags: "Bill Okoyo, Karl Williams, Steve Otieno, Men",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 10,
    title: "Resolution Now.",
    headline: "Resolution insurance renew sponsorship with Impala.",
    image_1: rilSponsorPhoto,
    image_2: rilSponsorPhoto1,
    type: "article",
    tags: "Resolution Insurance, Sponsorships, C2C, Club",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Sponsor",
  },
  {
    id: 11,
    title: "Tokyo 2020 Squad Returns.",
    headline:
      "Impala ladies among squad that flew in this morning from tokyo olympics.",
    image_1: olympicsLadies,
    image_2: olympicsLadies2,
    type: "article",
    tags: "Tokyo 2020, Olympics, Women",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 12,
    title: "Ajo on his journey so far.",
    headline: "Anthony Jerym talks on what its been like as an Impala.",
    image_1: ajoKenya,
    image_2: ajo,
    type: "feature",
    tags: "Kenya 15s, Kenya Cup, Academy, Men",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 13,
    title: "Transfer News.",
    headline: "2021 transfer window: Onsomu to leave the club",
    image_1: onsomuNondies,
    image_2: onsomu,
    type: "news",
    tags: "Samson Onsomu, Kenya Cup, Sam Kimakwa, Men, Club",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 14,
    title: "Catch up with Christabel Lindo.",
    headline:
      "Impala ladies among squad that flew in this morning from tokyo olympics.",
    image_1: tata,
    image_2: tataRunning,
    type: "feature",
    tags: "Ladies, Tokyo Olympics, Tata, Christabel, Women",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 15,
    title: "Alpha Academy.",
    headline: "Shaping lives, one player at a time.",
    image_1: alphaAcademy,
    image_2: kakaiAlpha,
    type: "feature",
    tags: "Alpha Academy, Age Grade,Club",
    created: "2022-01-07T00:22:25.804188+03:00",
    posted: "2022-01-07T00:22:25.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 16,
    title: "Tokyo 2020.",
    headline: "Impala ladies to represent the country in this years olympics",
    image_1: stella,
    image_2: ladiesRun,
    type: "feature",
    tags: "Ladies, Stella,Diana, Christabel, Women",
    created: "2021-12-19T00:13:58.804188+03:00",
    posted: "2021-12-19T00:13:58.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 17,
    title: "2021-2022 Technical Bench",
    headline: "Get top know this season's technical bench.",
    image_1: muchiri,
    image_2: physio,
    type: "feature",
    tags: "Club, Men, Kenya Cup",
    created: "2022-01-07T00:22:25.804188+03:00",
    posted: "2022-01-07T00:22:25.804188+03:00",
    author: "Impala Media",
  },
  {
    id: 18,
    title: "Website Built by Steve Shammah.",
    headline:
      "Frontend of the application. Data used may be random and/or inaccurate. ",
    image_1: coding,
    image_2: situationControl,
    type: "feature",
    tags: "React Js, Django, Javascript, Python, API, Fullstack Development, Club",
    created: "2022-01-07T00:22:25.804188+03:00",
    posted: "2022-01-07T00:22:25.804188+03:00",
    author: "Steve Shammah",
  },
];
