import { createContext } from "react";

export const teamContext = createContext();

export const TeamState = (props) => {
  const players = [
    {
      id: 0,
      name: "Steve Shammah",
      daysTrained: 6,
      daysMissed: 4,
      appearances: 60,
      dob: "26/2/1996",
      year: 1996,
      team: "swaras",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 1,
      name: "Tyson Okoth",
      daysTrained: 9,
      daysMissed: 1,
      appearances: 60,
      dob: "26/2/1996",
      year: 1996,
      team: "gazelles",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 2,
      name: "Nato Simiyu ",
      daysTrained: 8,
      daysMissed: 2,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "gazelles",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 3,
      name: "Dancun Ekasi ",
      daysTrained: 7,
      daysMissed: 3,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "swaras",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 4,
      name: "Sammy Oliech",
      daysTrained: 3,
      daysMissed: 7,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "ladies",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 5,
      name: "Paul Mutsami",
      daysTrained: 5,
      daysMissed: 5,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "ladies",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 6,
      name: "Patrick Mutuku",
      daysTrained: 2,
      daysMissed: 8,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "ladies",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 7,
      name: "Richard Asante ",
      daysTrained: 4,
      daysMissed: 6,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "ladies",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 8,
      name: "Valentino Cosmas ",
      daysTrained: 2,
      daysMissed: 8,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "ladies",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 9,
      name: "Clinton Musonye",
      daysTrained: 10,
      daysMissed: 0,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "swaras",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 10,
      name: "Martin Juma",
      daysTrained: 9,
      daysMissed: 1,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "ladies",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 11,
      name: "George Okowa",
      daysTrained: 4,
      daysMissed: 6,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "boks",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 12,
      name: "Quinto Oongo",
      daysTrained: 4,
      daysMissed: 6,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "boks",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 13,
      name: "Anthony Nyandigisi",
      daysTrained: 4,
      daysMissed: 6,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "boks",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
    {
      id: 14,
      name: "Martin Musau",
      daysTrained: 4,
      daysMissed: 6,
      appearances: 400,
      dob: "1/1/1988",
      year: 1988,
      team: "boks",
      socials: [{ instagram: "steveshammah_", twitter: "steveshammah_" }],
      phone: "795058630",
      email: "shammahranks@gmail.com",
    },
  ];

  return (
    <teamContext.Provider value={{ players }}>
      {props.children}
    </teamContext.Provider>
  );
};

export default TeamState;
